name: Python CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        cd test
        python -m unittest discover

  validation:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: validation
      url: ${{ secrets.VAL_ENV }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run validation
      run: |
        cd val
        python -m unittest discover

  deploy:
    needs: validation
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ secrets.PRD_ENV }}
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        # Add your deployment commands here
